export default [
  { text: "سبحان الله", category: "tasbeeh" },
  { text: "الحمد لله", category: "tasbeeh" },
  { text: "الله أكبر", category: "tasbeeh" },
  { text: "لا إله إلا الله", category: "tajdeed" },
  { text: "سبحان الله وبحمده", category: "tasbeeh" },
  { text: "سبحان الله العظيم", category: "tasbeeh" },
  { text: "سبحان الله والحمد لله", category: "tasbeeh" },
  { text: "سبحان الله بكرةً وأصيلاً", category: "tasbeeh" },
  { text: "الحمد لله رب العالمين", category: "tasbeeh" },
  {
    text: "سبحان الله والحمد لله ولا إله إلا الله والله أكبر",
    category: "tasbeeh",
  },
  { text: "اللهم اغفر لي", category: "duaa" },
  { text: "اللهم ارحمني", category: "duaa" },
  { text: "اللهم ارزقني", category: "duaa" },
  { text: "الحمد لله حمداً كثيراً طيباً مباركاً فيه", category: "tasbeeh" },
  { text: "لا حول ولا قوة إلا بالله", category: "tasbeeh" },
  { text: "أستغفر الله", category: "tasbeeh" },
  { text: "اللهم صلِّ على محمد", category: "tasbeeh" },
  { text: "اللهم أسألك الحكمة في القول والعمل", category: "duaa" },
  { text: "اللهم بارك على محمد وآل محمد", category: "tasbeeh" },
  { text: "اللهم اكفني بحلالك عن حرامك", category: "duaa" },
  { text: "اللهم اكفني بطاعتك عن معصيتك", category: "duaa" },
  { text: "اللهم آت سيدنا محمداً الوسيلة والفضيلة", category: "duaa" },
  { text: "أعوذ بالله من الشيطان الرحيم", category: "duaa" },
  { text: "أعوذ بالله من عذاب القبر", category: "duaa" },
  { text: "أعوذ بالله من فتنة الدجال", category: "duaa" },
  { text: "اللهم إني أسألك الخير كله", category: "duaa" },
  { text: "اللهم إني أعوذ بك من الشر كله", category: "duaa" },
  { text: "لا إله إلا أنت سبحانك إني كنت من الظالمين", category: "tasbeeh" },
  { text: "حسبي الله ونعم الوكيل", category: "tasbeeh" },
  { text: "رضيت بالله رباً", category: "tajdeed" },
  { text: "رضيت بالإسلام ديناً", category: "tajdeed" },
  {
    text: "اللهم لك الحمد كما ينبغي لجلال وجهك وعظيم سلطانك",
    category: "tasbeeh",
  },
  { text: "اللهم ارض عن صحابة رسول الله", category: "tazkeer" },
  { text: "اللهم ارض عن عائشة أم المؤمنين", category: "tazkeer" },
  { text: "اللهم ارض عن أبي بكر وعمر وعثمان وعلي", category: "tazkeer" },
];
